name: Unit Tests
description: Run Unit Tests
runs:
  using: "composite"
  steps:
    - name: Run restore
      run: dotnet restore
      shell: bash
    - name: Run tests
      run: |
        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info
        curl -s https://codecov.io/bash > codecov && bash codecov
      shell: bash
