name: Dead Links
description: Run Dead Links Tests
runs:
  using: "composite"
  steps:
    - name: Build docs
      run: |
        npm ci
        npm run doc-prepare
        npm run doc-build
      shell: bash
