jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-dev$/ OR type = cron
      language: csharp
      solution: sdk-csharp.sln
      sudo: required
      dist: xenial
      dotnet: 2.2
      mono: latest
      install:
        - dotnet restore

      script:
        - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=$TRAVIS_BUILD_DIR/lcov.info
        - curl -s https://codecov.io/bash > codecov && bash codecov

    - stage: "Tests"
      name: "Documentation"
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-dev$/ OR type = cron
      stage: Tests
      language: node_js
      node_js: 8

      script:
        - docker-compose -f .ci/doc/docker-compose.yml run doc-tests node index

    - stage: Tests
      name: Dead link check
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-(dev|stable)$/ OR type = cron

      before_script:
        - npm run doc-prepare
        - npm run --prefix doc/framework clone-repos
        - gem install typhoeus
      script:
        - HYDRA_MAX_CONCURRENCY=20 npm run --prefix doc/framework dead-links

    - stage: "Deployments"
      name: "NuGet"
      if: tag IS present AND branch = master
      language: csharp
      solution: sdk-csharp.sln
      sudo: required
      dist: xenial
      dotnet: 2.2
      mono: latest
      install:
        - dotnet restore

      script:
        # incompatibilities with msbuild, so building with .net core instead
        - dotnet build $TRAVIS_BUILD_DIR/Kuzzle/Kuzzle.csproj -c Release
        - dotnet build $TRAVIS_BUILD_DIR/Kuzzle.Tests/Kuzzle.Tests.csproj

      deploy:
        skip_cleanup: true
        email: support@kuzzle.io
        provider: script
        script: bash deploy.sh
