language: csharp
solution: sdk-csharp.sln
sudo: required
dist: xenial
dotnet: 2.2
mono: latest
addons:
  apt:
    packages:
      - nuget
install:
  - dotnet restore

script:
  - dotnet build $TRAVIS_BUILD_DIR/Kuzzle/Kuzzle.csproj -c Release

deploy:
  skip_cleanup: true
  email: support@kuzzle.io
  provider: script
  script: bash deploy.sh
