language: csharp
solution: sdk-csharp.sln
install:
  - nuget restore sdk-csharp.sln

script:
  - dotnet build Kuzzle/Kuzzle.csproj -c Release

deploy:
  skip_cleanup: true
  provider: script
  email: support@kuzzle.io
  script:
    - nuget pack Kuzzle/Kuzzle.nuspec -OutputFileNamesWithoutVersion
    - nuget push kuzzlesdk.nupkg -ApiKey ${NUGET_API_KEY} -Source nuget.org
  on:
    repo: kuzzleio/sdk-csharp
    all_branches: true
    condition: $TRAVIS_BRANCH = master
