language: csharp
solution: sdk-csharp.sln
sudo: required
dist: xenial
dotnet: 2.2
mono: latest
install:
  - dotnet restore

script:
  # incompatibilities with msbuild, so building with .net core instead
  - dotnet build $TRAVIS_BUILD_DIR/Kuzzle/Kuzzle.csproj -c Release
  - dotnet build $TRAVIS_BUILD_DIR/Kuzzle.Tests/Kuzzle.csproj
  - dotnet test

deploy:
  skip_cleanup: true
  email: support@kuzzle.io
  provider: script
  script: bash deploy.sh
