
jobs:
  include:
    - name: Unit Tests
      language: csharp
      solution: sdk-csharp.sln
      sudo: required
      dist: xenial
      dotnet: 2.2
      mono: latest
      install:
        - dotnet restore

      script:
        # incompatibilities with msbuild, so building with .net core instead
        - dotnet build $TRAVIS_BUILD_DIR/Kuzzle/Kuzzle.csproj -c Release
        - dotnet build $TRAVIS_BUILD_DIR/Kuzzle.Tests/Kuzzle.Tests.csproj
        - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=$TRAVIS_BUILD_DIR/lcov.info
        - curl -s https://codecov.io/bash > codecov && bash codecov

      deploy:
        skip_cleanup: true
        email: support@kuzzle.io
        provider: script
        script: bash deploy.sh

    - name: Documentation tests
      stage: Tests
      language: node_js
      node_js: 8

      script:
        - docker-compose -f .ci/doc/docker-compose.yml run doc-tests node index
