name: Deploy
description: Run Deploy
runs:
  using: "composite"
  steps:
    - name: Run restore
      run: dotnet restore
      shell: bash
    - name: Run Deploy
      run: |
        dotnet build $TRAVIS_BUILD_DIR/Kuzzle/Kuzzle.csproj -c Release
        dotnet build $TRAVIS_BUILD_DIR/Kuzzle.Tests/Kuzzle.Tests.csproj
        bash deploy.sh
      shell: bash
