---

snippets:
  mount: /mnt
  path: doc/**/snippets/*.test.yml
  templates: /mnt/.ci/doc/templates

runners:
  default: csharp

  csharp:
    service: doc-runner-csharp
    path: /var/snippets/csharp
    lint:
      cmd: echo "lint me master"
    build:
      cmd: dotnet build /mnt/Kuzzle/Kuzzle.csproj && mv /mnt/Kuzzle/bin/Debug/netstandard2.0/Kuzzle.dll /var/snippets/csharp/.
    run:
      cmd: dotnet script {{ snippet.source }}
