version: '3'

services:
  kuzzle:
    image: kuzzleio/kuzzle
    ports:
      - "7512:7512"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - elasticsearch
    container_name: kuzzle
    environment:
      - kuzzle_services__db__client__host=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - NODE_ENV=production

  redis:
    image: redis:5

  elasticsearch:
    image: kuzzleio/elasticsearch:5.6.10
    ulimits:
      nofile: 65536
    environment:
      - cluster.name=kuzzle
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"

  doc-tests:
    image: kuzzleio/snippets-tests
    privileged: true
    depends_on:
      - kuzzle
      - doc-runner-csharp
    volumes:
      - ../..:/mnt
      - /var/run/docker.sock:/var/run/docker.sock
      - snippets:/var/snippets
    environment:
      - CONFIG_FILE=/mnt/.ci/doc/config.yml

  doc-runner-csharp:
    image: kuzzleio/doc-runner:csharp
    command: tail -f /dev/null
    volumes:
      - ../..:/mnt
      - snippets:/var/snippets

  # doc-runner-web:
  #   image: buildkite/puppeteer:latest
  #   command: >
  #     bash -c '
  #       mkdir -p /var/snippets/web;
  #       apt-get update;
  #       apt-get install -y curl;
  #       npm install -g \
  #         eslint \
  #         eslint-plugin-html \
  #         eslint-plugin-import \
  #         eslint-plugin-node \
  #         eslint-plugin-promise \
  #         eslint-plugin-standard;
  #       touch /tmp/runner_ready_to_lint;
  #       cd /var/snippets/web;
  #       cp /mnt/.ci/doc/puppeteer.js /var/snippets/web/;
  #       npm install \
  #         /mnt/ \
  #         puppeteer;
  #       touch /tmp/runner_is_ready;
  #       tail -f /dev/null
  #     '
  #   volumes:
  #     - ../..:/mnt
  #     - snippets:/var/snippets

  # doc-runner-webpack:
  #   image: buildkite/puppeteer:latest
  #   command: >
  #     bash -c '
  #       mkdir -p /var/snippets/webpack;
  #       apt-get update;
  #       apt-get install -y curl;
  #       npm install -g \
  #         eslint \
  #         eslint-plugin-html \
  #         eslint-plugin-import \
  #         eslint-plugin-node \
  #         eslint-plugin-promise \
  #         eslint-plugin-standard;
  #       touch /tmp/runner_ready_to_lint;
  #       cd /var/snippets/webpack;
  #       cp /mnt/.ci/doc/puppeteer.js /var/snippets/webpack/;
  #       cp /mnt/.ci/doc/webpackBuild.js /var/snippets/webpack/;
  #       npm install \
  #         /mnt/ \
  #         babel-loader \
  #         @babel/core \
  #         puppeteer \
  #         html-webpack-plugin \
  #         webpack \
  #         webpack-cli;
  #       touch /tmp/runner_is_ready;
  #       tail -f /dev/null
  #     '
  #   volumes:
  #     - ../..:/mnt
  #     - snippets:/var/snippets

volumes:
  snippets:
