name: Deploy Prod to NuGet

on:
   push:
     branches:
       - master
       - 1-stable
  

jobs:
  deploy-prod:
    name: Unit Tests csharp ${{ matrix.dotnet }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['2.2']
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - uses: ./.github/actions/deploy
